version: "3.9"

services:
  streamlit-app:
    build: .
    ports:
      - "7777:7777"
    volumes:
      # Mount the whole project for hot reload
      - ./:/app
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONUNBUFFERED=1
