services:
  streamlit-app:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - ./:/app
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONUNBUFFERED=1

  jupyter-notebook:
    image: quay.io/jupyter/datascience-notebook:2025-02-12
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/
