version: "3.9"

services:
  streamlit-app:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws:ro
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONUNBUFFERED=1

