services:
  streamlit-app:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - ./:/app
    environment:
      STREAMLIT_SERVER_HEADLESS: true
      PYTHONUNBUFFERED: 1
      LANGSMITH_TRACING: true
      LANGSMITH_ENDPOINT: ${LANGSMITH_ENDPOINT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}

  jupyter-notebook:
    image: quay.io/jupyter/datascience-notebook:2025-02-12
    command: bash -c "pip install -r /home/jovyan/work/requirements.txt && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - "9999:9999"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ~/.aws:/home/jovyan/.aws
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGSMITH_TRACING: true
      LANGSMITH_ENDPOINT: ${LANGSMITH_ENDPOINT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
  
  langgraph:
    build: .
    container_name: llm-playground-langgraph
    command: langgraph dev --host 0.0.0.0 --port 2024
    ports:
      - "2024:2024"
    volumes:
      - .:/app